services:
    backend:
        depends_on:
            db: 
                condition: service_healthy
        build:
            context: ./petday-backend
            dockerfile: Dockerfile.backend
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
            - DB_HOST=db
            - DB_NAME=dbpetday
            - DB_USER=root
            - DB_PASS=1234
            - JWT_SECRET=SQDSASHU   
        networks:
            - petday-network
    
    frontend:
        build:
            context: ./petday-frontend
            dockerfile: Dockerfile.frontend
        ports:
            - "3001:3001"
        depends_on:
            - backend
        networks:
            - petday-network
    
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: dbpetday
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - petday-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s

volumes:
    db-data:

networks:
    petday-network:
        driver: bridge